version: '3.8'

services:
  api:
    build: .
    image: zimmerman-ai-api
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      # path to be changed in deployment, this path assumes as part of DX central repo
      - ../dx.backend/parsed-data-files:/parsed-data-files
    ports:
      - 5000:5000
    env_file:
      - .env
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
